### ISSUE TITLE
Move grammar to an official grammars repository

### ISSUE THREAD

**Issue by KvanTTT** [cy6erGn0m/kotlin-antlr4-grammar#3]
Please, move your grammar here for community: https://github.com/antlr/grammars-v4

**Comment by marcinwyszynski** [comment]
+1

**Comment by cy6erGn0m** [comment]
@KvanTTT @marcinwyszynski can I just make a pull request to antlr? Do I need to pass through any special process to get my grammar included?

**Comment by KvanTTT** [comment]
1. Add license (header or separated file).
2. Add pom.xml file for maven plugin (see [tsql](https://github.com/antlr/grammars-v4/tree/master/tsql) for example).
3. Add kotlin record to the common pom.xml file ([here](https://github.com/antlr/grammars-v4/blob/master/pom.xml)).
4. Ideally add some kotlin language files for tests to "examples" directory (also see tsql grammar).
5. Make pull request :)
6. (optional) Add info that grammar has been moved to an official grammars repository.

**Comment by KvanTTT** [comment]
Moved by myself: https://github.com/antlr/grammars-v4/tree/master/kotlin
