### ISSUE TITLE
What is the state of this project?

### ISSUE THREAD

**Issue by ghostbuster91** [cy6erGn0m/kotlin-antlr4-grammar#4]
Is the project dead or something? 

Also if you are not going to maintain it anymore please let me know if I can fork it and continue work by my own. I notice that you work for JetBrains, so maybe they are planning to create such thing (or already created) and that's the reason why abandoned it.

**Comment by KvanTTT** [comment]
Please move this grammar to an [official grammars repository](https://github.com/antlr/grammars-v4) if want to contribute.

UPDATE: already moved by myself: https://github.com/antlr/grammars-v4/tree/master/kotlin

**Comment by cy6erGn0m** [comment]
@KvanTTT Very great! Thanks!

**Comment by KvanTTT** [comment]
What license of your grammar? I'm gonna include it there.

**Comment by cy6erGn0m** [comment]
I generally use Apache 2 license but I have no idea whether it is applicable to grammars or not

**Comment by KvanTTT** [comment]
Why not? I'll add Apache 2 license file there. Or you can do it by own :)
